databases:
  - name: mysitedb
    plan: free
    databaseName: sales
    user: sales

services:
  - type: web
    plan: free
    name: salesproject
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn salesproject.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mysitedb
          property: connectionString
      - key: WEB_CONCURRENCY
        value: 4